# Task 1:

# Question 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def throws():
    return 5/0

try:
    throws()
except ZeroDivisionError:
    print("Divide by Zero Error")
except Exception:
    print("Exception Block")
finally:
    print("Finally Block")

Divide by Zero Error
Finally Block


# Question 2.
# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]
# Output should come as below:
# Americans play Baseball.
# Americans play Cricket.
# Americans watch Baseball.
# Americans watch Cricket.
# Indians play Baseball.
# Indians play Cricket.
# Indians watch Baseball.
# Indians watch Cricket.

In [3]:
# Solution 
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Here List Comprehension is used to generate list
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]

for sentence in sentence_list: # list print 
    print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task 2:

# Question 1.
# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [25]:
import numpy as np # import numpy 
# generate array 
x = np.array([1, 2, 3, 4]) # input vector 1 D array 
N = 3                      # N is number of columns in output 
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [26]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [27]:
x = np.array([1, 2, 3, 4])
np.vander(x)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [28]:
np.vander(x, increasing=True) # Increasing power so True 

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [29]:
np.linalg.det(np.vander(x))

11.99999999999999